name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        kind: ['alpine', 'amazonlinux1', 'centos', 'debian', 'ubuntu']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: "hayd/${{ matrix.kind }}-deno"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ${{ matrix.kind }}.dockerfile
        cache: true
        tags: "latest,${{ steps.get_version.outputs.VERSION }}"
    - name: Publish Docker Legacy
      if: matrix.kind != 'amazonlinux1'
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: "hayd/deno"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: ${{ matrix.kind }}.dockerfile
        cache: true
        tags: "${{ matrix.kind }},${{ matrix.kind }}-${{ steps.get_version.outputs.VERSION }}"
  build_alpine_latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Publish Docker Legacy Alpine
      uses: elgohr/Publish-Docker-Github-Action@2.7
      with:
        name: "hayd/deno"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: alpine.dockerfile
        cache: true
        tags: "latest,${{ steps.get_version.outputs.VERSION }}"
